#!/bin/sh

gitrev=$(git rev-parse HEAD)

rm -rf prod


npm run build

make webserver-prod

ssh mondrian <<CMDS
rm -rf /app/mondrian/releases/$gitrev
mkdir -p /app/mondrian/releases/$gitrev
CMDS

aws s3 sync build/prod/ s3://mondrian-static/build/ --profile ballpoint-deploy \
  --region us-east-2 \
  --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

scp bin/webserver mondrian:/app/mondrian/releases/$gitrev

ssh mondrian <<CMDS
cd /app/mondrian/releases
rm current
ln -s /app/mondrian/releases/$gitrev current
sudo service mondrian restart
CMDS
